### ISSUE TITLE
Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

### ISSUE THREAD

**Issue by tgaktas** [CrazyWolf13/auto_gfpgan-installer#1]
venv "C:\Users\pc\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Traceback (most recent call last):
  File "C:\Users\pc\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "C:\Users\pc\stable-diffusion-webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\pc\stable-diffusion-webui\modules\launch_utils.py", line 356, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .

**Comment by CrazyWolf13** [comment]
> venv "C:\Users\pc\stable-diffusion-webui\venv\Scripts\Python.exe" Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] Version: v1.6.0 Commit hash: 5ef669de080814067961f28357256e8fe27544f4 Traceback (most recent call last): File "C:\Users\pc\stable-diffusion-webui\launch.py", line 48, in main() File "C:\Users\pc\stable-diffusion-webui\launch.py", line 39, in main prepare_environment() File "C:\Users\pc\stable-diffusion-webui\modules\launch_utils.py", line 356, in prepare_environment raise RuntimeError( RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check Press any key to continue . . .

Please share more about what GPU you have and how if you selected NVIDIA GPU or not

**Comment by CrazyWolf13** [comment]
> venv "C:\Users\pc\stable-diffusion-webui\venv\Scripts\Python.exe"
> Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
> Version: v1.6.0
> Commit hash: 5ef669de080814067961f28357256e8fe27544f4
> Traceback (most recent call last):
>   File "C:\Users\pc\stable-diffusion-webui\launch.py", line 48, in <module>
>     main()
>   File "C:\Users\pc\stable-diffusion-webui\launch.py", line 39, in main
>     prepare_environment()
>   File "C:\Users\pc\stable-diffusion-webui\modules\launch_utils.py", line 356, in prepare_environment
>     raise RuntimeError(
> RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
> Press any key to continue . . .

Also this has not been tested with stable diffusion webui, but it should work nontheless.

**Comment by tgaktas** [comment]
> NVIDIA GPU

I did not install any programs because it is automatic.

my rx570 graphics card

**Comment by tgaktas** [comment]
> > venv "C:\Users\pc\stable-diffusion-webui\venv\Scripts\Python.exe" 
> > Python 3.10.11 (tags/v3.10.11:7d4cc5a, 5 Nisan 2023, 00:38:17) [MSC v. 1929 64 bit (AMD64)] 
> > Sürüm: v1.6.0 
> > Karma işlemi: 5ef669de080814067961f28357256e8fe27544f4 
> > Geri izleme (en son çağrı): 
> > Dosya "C:\Users\pc\stable-diffusion-webui\launch.py", satır 48, ana bölümde 
> > ( ) 
> > "C:\Users\pc\stable-diffusion-webui\launch.py" dosyası, 39. satır, ana 
> > hazır_environment() 
> > dosyasında "C:\Users\pc\stable-diffusion-webui\modules\launch_utils.py" dosyası , satır 356, hazır_environment 
> > yükselt RuntimeError( 
> > RuntimeError: Torch GPU'yu kullanamıyor; bu kontrolü devre dışı bırakmak için COMMANDLINE_ARGS değişkenine --skip-torch-cuda-test ekleyin Devam etmek için 
> > herhangi bir tuşa basın. . .
> 
> Ayrıca bu, kararlı difüzyon webui'si ile test edilmemiştir, ancak yine de çalışması gerekir.

Where can I enter webui?

**Comment by CrazyWolf13** [comment]
> > NVIDIA GPU
> 
> I did not install any programs because it is automatic.
> 
> my rx570 graphics card
> 
> 

The script asks you if you have a compatible nvidia gpu, then it will install nvidia specific torch version and then you have to manually install cuda as I can't just include nvidia software.

**Comment by CrazyWolf13** [comment]
> > > venv "C:\Users\pc\stable-diffusion-webui\venv\Scripts\Python.exe" 
> > > Python 3.10.11 (tags/v3.10.11:7d4cc5a, 5 Nisan 2023, 00:38:17) [MSC v. 1929 64 bit (AMD64)] 
> > > Sürüm: v1.6.0 
> > > Karma işlemi: 5ef669de080814067961f28357256e8fe27544f4 
> > > Geri izleme (en son çağrı): 
> > > Dosya "C:\Users\pc\stable-diffusion-webui\launch.py", satır 48, ana bölümde 
> > > ( ) 
> > > "C:\Users\pc\stable-diffusion-webui\launch.py" dosyası, 39. satır, ana 
> > > hazır_environment() 
> > > dosyasında "C:\Users\pc\stable-diffusion-webui\modules\launch_utils.py" dosyası , satır 356, hazır_environment 
> > > yükselt RuntimeError( 
> > > RuntimeError: Torch GPU'yu kullanamıyor; bu kontrolü devre dışı bırakmak için COMMANDLINE_ARGS değişkenine --skip-torch-cuda-test ekleyin Devam etmek için 
> > > herhangi bir tuşa basın. . .
> > 
> > Ayrıca bu, kararlı difüzyon webui'si ile test edilmemiştir, ancak yine de çalışması gerekir.
> 
> Where can I enter webui?

My tools is created for gfpgan not stable-diffusion web-ui 😉
However it should work

**Comment by tgaktas** [comment]
If there was a video maybe I could make it.

Otherwise I tried all methods to install gfpgan :(

**Comment by CrazyWolf13** [comment]
> If there was a video maybe I could make it.
> 
> Otherwise I tried all methods to install gfpgan :(

Please answer my question, so I can help you:
Did you specify yes to: "Do you have a nvidia graphics card?" Or did you just press enter to set default?

**Comment by CrazyWolf13** [comment]
> If there was a video maybe I could make it.
> 
> Otherwise I tried all methods to install gfpgan :(

My project aims to simplify the installation of gfpgan.

It is basically you click and then hit some times enter and there you go gfpgan in installed, the error you provided shows that you have a running virtual python enviroment.

**Comment by tgaktas** [comment]
> > If there was a video maybe I could make it.
> > Otherwise I tried all methods to install gfpgan :(
> 
> Please answer my question, so I can help you: Did you specify yes to: "Do you have a nvidia graphics card?" Or did you just press enter to set default?

GPU : Radeon RX 570 Series

**Comment by tgaktas** [comment]
> > Video olsaydı belki yapabilirdim.
> > Aksi halde gfpgan'ı kurmak için tüm yöntemleri denedim :(
> 
> Projem gfpgan kurulumunu basitleştirmeyi amaçlıyor.
> 
> Temel olarak tıklayıp ardından birkaç kez enter tuşuna basıyorsunuz ve orada gfpgan kurulu oluyor, sağladığınız hata, çalışan bir sanal python ortamınız olduğunu gösteriyor.

I tried it and it came up to "DONE", but I don't know how to use it

**Comment by CrazyWolf13** [comment]
> > > Video olsaydı belki yapabilirdim.
> > > Aksi halde gfpgan'ı kurmak için tüm yöntemleri denedim :(
> > 
> > Projem gfpgan kurulumunu basitleştirmeyi amaçlıyor.
> > 
> > Temel olarak tıklayıp ardından birkaç kez enter tuşuna basıyorsunuz ve orada gfpgan kurulu oluyor, sağladığınız hata, çalışan bir sanal python ortamınız olduğunu gösteriyor.
> 
> I tried it and it came up to "DONE", but I don't know how to use it

Please tell me what you want to achieve otherwise I cannot help you.

**Comment by CrazyWolf13** [comment]
> > > Video olsaydı belki yapabilirdim.
> > > Aksi halde gfpgan'ı kurmak için tüm yöntemleri denedim :(
> > 
> > 
> > Projem gfpgan kurulumunu basitleştirmeyi amaçlıyor.
> > Temel olarak tıklayıp ardından birkaç kez enter tuşuna basıyorsunuz ve orada gfpgan kurulu oluyor, sağladığınız hata, çalışan bir sanal python ortamınız olduğunu gösteriyor.
> 
> I tried it and it came up to "DONE", but I don't know how to use it

Some more info, by default my script installs the non gpu version of torch (uses CPU) but in your case you need a special version for amd to get gpu support, which is not available for windows, altough amd support isn't that developed, so you have to do your own research from there on.

**Note: This only works on Linux not on Windows or MacOS**
If you are on windows, either get a nvidia GPU or leave it as it is and continue using the CPU package.

Uninstall CPU Package if you are on linux
`pip uninstall torch torchaudio torchvision`

And install this packages to install torch for amd devices.
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.6`
