### ISSUE TITLE
error running video.py

### ISSUE THREAD

**Issue by sergeivich** [CrazyWolf13/auto_gfpgan-installer#2]
Portraitarchiv_Crawler\GFPGAN\video.py", line 7
    < !DOCTYPE html >
    ^
SyntaxError: invalid syntax

**Comment by CrazyWolf13** [comment]
Please retry with the new release, just remove the folder and all contents, download the new batch file then double click it.

Why are you running video.py? If I may ask.

My script also does not mess with any other stuff.

**Comment by sergeivich** [comment]
made a mistake, this was actually for a different project https://github.com/butaixianran/VIdeo_Upscaler_by_GFPGAN, sorry about that!
