### ISSUE TITLE
how do you launch GFPGAN

### ISSUE THREAD

**Issue by spaceyspeed** [CrazyWolf13/auto_gfpgan-installer#3]
I got everything installed but don't know how to launch the program/gui on win 11.

**Comment by CrazyWolf13** [comment]
Hi 
Thanks for using my tool! 🔥

GFPGAN itself is a command-line only tool.

Made to easily integrate into any python project.

But you can just launch a commandline/terminal window and navigate to the folder where you installed gfpgan to:

Then put your photos in the folder inputs/whole_imgs, then finished photos will then be in results folder.

And run the following command:
`python inference_gfpgan.py -i inputs/whole_imgs -o results -v 1.3 -s 2`

**Comment by rraj000000** [comment]
![Screenshot 2024-05-31 105247](https://github.com/CrazyWolf13/auto_gfpgan-installer/assets/171314980/0992a6ad-4739-4e45-9078-697d94dabe02)

**Comment by rraj000000** [comment]
how to solve that?

**Comment by CrazyWolf13** [comment]
Can you try `pip install cv2` ?

**Comment by CrazyWolf13** [comment]
@spaceyspeed @rraj000000  
Could you figure it out, or do you need further help?

**Comment by hesicos** [comment]
Can you help me with these errors. The installation was completed successfully. I used the command indicated on this page but was unsuccessful. Thank you.

![errorgfpgan](https://github.com/CrazyWolf13/auto_gfpgan-installer/assets/174639974/7b408193-142b-4c36-b3fd-76d3496e4fb4)

**Comment by CrazyWolf13** [comment]
Hi
could you try this:

```
pip uninstall numpy
pip install numpy<2
```

**Comment by hesicos** [comment]
> Hi could you try this:
> 
> ```
> pip uninstall numpy
> pip install numpy<2
> ```

Thank you for your help, this resolved the error, but another one appeared.

![newerror](https://github.com/CrazyWolf13/auto_gfpgan-installer/assets/174639974/cd1e9e6d-d45b-42f2-9c27-aa8a2955e248)

**Comment by CrazyWolf13** [comment]
What happens if you run
```
pip install torchvision
pip install --upgrade torchvision
```

Have you selected with or without CUDA?

**Comment by hesicos** [comment]
Unfortunately the same error persists.
I selected without CUDA.

**Comment by CrazyWolf13** [comment]
> Unfortunately the same error persists. I selected without CUDA.

https://github.com/CrazyWolf13/auto_gfpgan-installer?tab=readme-ov-file

take a look at the steps recommended on the warning at the top of the readme, they should solve your problem :)

**Comment by hesicos** [comment]
Are you referring to this change?

%localappdata%\Programs\Python\Python311\Scriptsdegradations.py edit with notepad from torchvision.transforms.functional_tensor import rgb_to_grayscalefrom torchvision.transforms.functional import rgb_to_grayscale

Only Python310 was automatically installed and the degradations.py file does not exist in the Scripts folder.

**Comment by CrazyWolf13** [comment]
that is not good then, could you fully remove the gfpgan folder and re-run the script again?

after installing python11 ?

You can install python11 by running `winget install Python.Python.3.11`

**Comment by CrazyWolf13** [comment]
I'll close this ticket, as it's getting a bit messy, 

@hesicos if your issue persists after installing python11 and running the script again, after removing the gfpgan folder and uninstalling python, please create a new ticket.
